base_files:
  - "LICENSE"
  - "README.md"
  - "requirements.txt"
  - "user_config.otvision.yaml"
  - "track.py"
  - "detect.py"
  - "convert.py"
configurations:
  - package_path: OTVision
    files:
      - "install.cmd"
    suffix: "win"
    output_file_name: otvision
    additional_requirements:
      - ""
  - package_path: OTVision
    files:
      - "install.sh"
    suffix: "linux"
    output_file_name: otvision
    additional_requirements:
      - ""
  - package_path: OTVision
    files:
      - "install.sh"
    suffix: "macos"
    output_file_name: OTVision
    additional_requirements:
      - ""
  - package_path: OTVision
    files:
      - "install.cmd"
    suffix: "win-cuda"
    output_file_name: otvision
    additional_requirements:
      - "https://download.pytorch.org/whl/cu116"
  - package_path: OTVision
    files:
      - source: "install.sh"
    suffix: "linux-cuda"
    output_file_name: OTVision
    additional_requirements:
      - "https://download.pytorch.org/whl/cu116"
