---
name: Build Nightly Version

on:
  # Creates Nightly Release of main
  # Needs: secrets.PLATOMO_BUILDER_ACCESS
  push:
    branches:
      - main

jobs:
  test:
    uses: './.github/workflows/test.yml'
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Update Version
        run: |
          cp OTVision/version.py version.py.backup
          echo "__version__ = $GITHUB_ENV" > ./OTVision/version.py
          cat version.py.backup |tail -n+2>> ./OTVision/version.py
          git config --local user.name actions-user
          git config --local user.email "actions@github.com" 
          git fetch
          git add *
          git commit -m "version update via workflow" 
          git push -f origin main
  create_nightly:
    needs: test
    uses: "platomo/GitHub-workflows/.github/workflows/reusable-create-release-with-assets.yml@main"
    secrets:
      PLATOMO_BUILDER_ACCESS: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
    with:
      package-version: nightly
      draft-release: false
      pre-release: true
      delete-existing: true

