---
name: Build Release Version

on:
  # Create release if tag is pushed to main.
  # Needs: secrets.PLATOMO_BUILDER_ACCESS
  push:
    tags:
      - "v*.*.*.*"

jobs:
  test:
    if: endsWith(github.event.base_ref, 'main')
    uses: './.github/workflows/test.yml'
  update_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Version
        run: |
          cp OTVision/version.py version.py.backup
          echo "__version__ = \"$GITHUB_REF_NAME\"" > ./OTVision/version.py
          cat version.py.backup |tail -n+2>> ./OTVision/version.py
          git branch -b
          git config --local user.name actions-user
          git config --local user.email "actions@github.com" 
          git fetch
          git add *
          git commit -m "version update via workflow" 
          git push -u origin main
  create_release:
    needs: test
    uses: "platomo/GitHub-workflows/.github/workflows/reusable-create-release-with-assets.yml@main"
    secrets:
      PLATOMO_BUILDER_ACCESS: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
    with:
      package-version: ${{ github.ref_name }}
      draft-release: false
      pre-release: false
      delete-existing: false

